### PR TITLE
Docker Based Implementation

### PR DESCRIPTION
**Pull request by ruddra**
Docker Based Implementation based on issue #12

### CODE REVIEW

**Comment by rakibtg** [comment]
@akimul Vai can you please check it in Ubuntu environment?

**Comment by ruddra** [comment]
@rakibtg apparently there are some issues in Ubuntu, maybe we can look into that together with @akimul  tomorrow?

**Comment by rakibtg** [comment]
@ruddra Sounds great!

**Comment by ruddra** [comment]
@rakibtg updated the PR

**Pull request merged**
